"""The agent service: run a workflow, record what it did.

Every run is persisted to `agent_investigations`, including the ones that were rejected.
An agent you cannot interrogate afterwards is an agent you cannot trust or improve, and
"the model said so" is not an audit entry.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from agent import model as agent_model
from agent import workflows
from backend.app.models.core import AgentInvestigation, Incident, User
from backend.app.services import audit
from shared.enums import AuditAction
from shared.timeutils import iso, utcnow

# What a run stores as its evidence: the retrieved facts and the judgement calls, never the
# whole outcome object (which carries the prose answer too).
_FACTS_KEYS = {
    "findings",
    "known",
    "unknown",
    "based_on",
    "rejected_numbers",
    "language",
    "method",
    # The responder path: what the fixed rules read, where the report placed the person, and
    # what the run actually wrote. Together they let an auditor re-derive the decision.
    "reading",
    "location",
    "created_requests",
    "model_calls",
    "report_id",
}


def model_status() -> dict[str, Any]:
    """What the language layer can actually do right now, and what it does instead."""
    return agent_model.status().to_dict()


def to_dict(row: AgentInvestigation) -> dict[str, Any]:
    return {
        "id": row.id,
        "trigger": row.trigger,
        "subject_type": row.subject_type,
        "subject_id": row.subject_id,
        "mode": row.mode,
        "status": row.status,
        "model": row.model_id,
        "response_text": row.response_text,
        "findings": row.findings,
        "tool_calls": row.tool_calls,
        "error": row.error,
        "duration_ms": row.duration_ms,
        "provenance": row.provenance,
        "created_at": iso(row.created_at),
    }


def _record(
    db: Session,
    outcome: dict[str, Any],
    *,
    actor: User | None,
    provenance: str = "derived",
) -> AgentInvestigation:
    row = AgentInvestigation(
        trigger=outcome.get("trigger", "incident"),
        subject_type=outcome.get("subject_type"),
        subject_id=outcome.get("subject_id"),
        prompt=str(outcome.get("asked") or outcome.get("ref_code") or "")[:2000],
        mode=outcome.get("mode", "deterministic"),
        status=outcome.get("status", "completed"),
        tool_calls=outcome.get("tool_calls") or [],
        findings={key: value for key, value in outcome.items() if key in _FACTS_KEYS},
        response_text=str(outcome.get("response_text") or ""),
        model_id=outcome.get("model"),
        error=outcome.get("error"),
        duration_ms=outcome.get("duration_ms"),
        # Inherited from what was investigated: a run over a rehearsal row is itself part of
        # that rehearsal, and has to be findable and removable as one.
        provenance=provenance,
        created_at=utcnow(),
    )
    db.add(row)
    # The id is generated by a column default, which SQLAlchemy only applies when it writes
    # the row. Without this flush the audit entry is filed against `entity_id=None`, and the
    # NOT NULL constraint on the audit table turns a successful run into a 500.
    db.flush()
    audit.record(
        db,
        action=AuditAction.AGENT_INVESTIGATION,
        entity_type="agent_investigation",
        entity_id=row.id,
        actor=actor,
        actor_kind="agent",
        new={"mode": row.mode, "status": row.status, "subject": row.subject_id},
        reason="agent run recorded",
        commit=False,
    )
    db.commit()
    return row


def investigate_incident(
    db: Session, incident: Incident, *, permissions: set[str] | None, actor: User | None = None
) -> dict[str, Any]:
    outcome = workflows.investigate(db, incident, permissions=permissions, viewer=getattr(actor, "username", "system"))
    outcome["subject_id"] = incident.id
    outcome["ref_code"] = incident.ref_code
    row = _record(db, outcome, actor=actor, provenance=incident.provenance or "derived")
    return {
        **to_dict(row),
        "ref_code": incident.ref_code,
        "known": outcome.get("known"),
        "unknown": outcome.get("unknown"),
        "note": outcome.get("note"),
        "rejected_numbers": outcome.get("rejected_numbers"),
    }


def respond(
    db: Session,
    text: str,
    *,
    permissions: set[str] | None,
    operator: User | None = None,
    report_id: str | None = None,
    incident_id: str | None = None,
) -> dict[str, Any]:
    """Answer one victim report and store the run, writes included.

    The request it files is committed by the assistance service on its own, the way it is for
    any operator action - so a model that dies halfway through leaves a real case behind, not a
    rolled-back suggestion of one. What this function adds to the stored row is the activity
    timeline and the outcome of the number check.
    """
    outcome = workflows.respond(
        db,
        text,
        permissions=permissions,
        operator=operator,
        report_id=report_id,
        incident_id=incident_id,
    )
    row = _record(db, outcome, actor=operator, provenance=outcome.get("provenance") or "derived")
    return {
        **to_dict(row),
        "report_id": outcome.get("report_id"),
        "created_requests": outcome.get("created_requests") or [],
        "model_calls": outcome.get("model_calls"),
        "reading": outcome.get("reading"),
        "location": outcome.get("location"),
        "rejected_numbers": outcome.get("rejected_numbers"),
        "note": outcome.get("note"),
    }


def chat(
    db: Session, *, user: User | None, question: str, district: str | None = None
) -> dict[str, Any]:
    outcome = workflows.answer_question(db, user, question, district=district)
    outcome.update(
        {"trigger": "chat", "subject_type": "user", "subject_id": user.id if user else None}
    )
    row = _record(db, outcome, actor=user)
    # `to_dict` describes the stored run; the reply-only fields (which language it answered
    # in, and the honesty note explaining how it was written) exist only in the outcome.
    return {
        **to_dict(row),
        "language": outcome.get("language"),
        "note": outcome.get("note"),
        "based_on": outcome.get("based_on"),
    }


def classify_text(
    db: Session, text: str, *, with_model: bool = False, actor: User | None = None
) -> dict[str, Any]:
    return workflows.classify(db, text, with_model=with_model)


def for_incident(db: Session, incident_id: str, limit: int = 10) -> list[dict[str, Any]]:
    rows = list(
        db.execute(
            select(AgentInvestigation)
            .where(AgentInvestigation.subject_id == incident_id)
            .order_by(AgentInvestigation.created_at.desc())
            .limit(limit)
        ).scalars()
    )
    return [to_dict(row) for row in rows]


def inventory() -> dict[str, Any]:
    """The tool sets, as names and descriptions, without running anything.

    Published because "what is the agent allowed to look at" must be answerable by reading
    the product, not by reading its source - and since the responder path can write, so must
    "what is it allowed to change", which is why each row carries `writes`.
    """
    from agent.tools import ResponderContext, build_read_tools, build_respond_tools

    def specs(markers: list[Any], *, group: str, writes: set[str]) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        for marker in markers:
            spec = getattr(marker, "tool_spec", {}) or {}
            name = spec.get("name")
            rows.append(
                {
                    "name": name,
                    "description": (spec.get("description") or "").strip(),
                    "arguments": sorted(
                        (spec.get("inputSchema", {}).get("json", {}) or {}).get("properties", {})
                    ),
                    "set": group,
                    "writes": name in writes,
                }
            )
        return rows

    # `db=None` is safe here: the tools close over the session but are never called, and a
    # permission set of nothing means every one of them would refuse even if they were.
    investigation = specs(build_read_tools(None, set()), group="investigation", writes=set())  # type: ignore[arg-type]
    responder_writes = {
        "create_assistance_request",
        "update_assistance_request",
        "notify_response_center",
        "send_victim_update",
    }
    response = specs(
        build_respond_tools(ResponderContext(db=None, permissions=set())),  # type: ignore[arg-type]
        group="response",
        writes=responder_writes,
    )
    tools = investigation + response
    return {
        # False now that one of the two sets can write. The write tools are named rather than
        # described: they are the whole of the agent's power to act and worth counting.
        "read_only": False,
        "count": len(tools),
        "tools": tools,
        "sets": {
            "investigation": {"count": len(investigation), "read_only": True},
            "response": {"count": len(response), "read_only": False},
        },
        "write_tools": sorted(responder_writes),
        "note": (
            "The investigation set can only read. The response set additionally files a help "
            "request, adds an internal note, queues a Response Center notice and sends a "
            "victim message; it cannot move a case status, and every one of the four runs "
            "through the same service an operator's own button calls."
        ),
    }


def stats(db: Session) -> dict[str, Any]:
    total = int(db.execute(select(func.count(AgentInvestigation.id))).scalar_one() or 0)
    by_mode = dict(
        db.execute(
            select(AgentInvestigation.mode, func.count(AgentInvestigation.id)).group_by(
                AgentInvestigation.mode
            )
        ).all()
    )
    by_status = dict(
        db.execute(
            select(AgentInvestigation.status, func.count(AgentInvestigation.id)).group_by(
                AgentInvestigation.status
            )
        ).all()
    )
    return {"total": total, "by_mode": by_mode, "by_status": by_status}
