"""Community routes - the five things a person can do on their phone.

Every response here answers the three questions the specification demands the
community side never leave open: did you receive it, who is doing what, when will
I hear again. The text is generated by `services.communication`, so it is the same
words in English and Nepali and never a model improvising a promise.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import desc, select
from sqlalchemy.orm import Session

from backend.app.deps import get_db, require_permission
from backend.app.models.core import AssistanceRequest, Incident, User
from backend.app.schemas import (
    AssistanceRequestIn,
    CancelIn,
    OfflineFlushIn,
    ReportIn,
)
from backend.app.services import assistance, audit, communication
from backend.app.services import community as community_service
from shared.timeutils import iso, utcnow

router = APIRouter(prefix="/community", tags=["community"])


@router.post("/reports")
def file_report(
    body: ReportIn,
    user: User = Depends(require_permission("community:report")),
    db: Session = Depends(get_db),
) -> dict:
    report, linked, request = community_service.submit_report(
        db,
        user=user,
        message=body.message,
        report_type=body.report_type,
        incident_type=body.incident_type,
        latitude=body.latitude,
        longitude=body.longitude,
        location_text=body.location_text,
        people_count=body.people_count,
        medical_need=body.medical_need,
        injuries=body.injuries,
        language=body.language,
        attachments=[a.model_dump() for a in body.attachments],
        client_timestamp=body.client_timestamp,
        submitted_offline=body.submitted_offline,
        needs_help=body.needs_help,
        help_types=body.help_types,
        incident_id=body.incident_id,
        immediate_danger=body.immediate_danger,
    )
    return {
        "report": community_service.report_to_dict(db, report),
        "incident": _public_incident(linked),
        "assistance_request": assistance.to_dict(db, request, victim_view=True) if request else None,
        "answer": _answer(report, linked, request),
        "what_happens_next": (
            communication.next_step(request.status, body.language)
            if request
            else _report_next_step(report, linked)
        ),
        "demo_mode": bool(report.demo_scenario_id),
    }


def _answer(report, linked, request) -> str:
    """One sentence telling the person what their message became."""
    language = report.language
    carried_on = (report.structured or {}).get("help_carried_on")
    if request is not None and carried_on:
        # Saying "a request was opened" when it was already open would be a lie about
        # the state of their own case, and the case number is the part they keep.
        return (
            f"तपाईंको अघिल्लो अनुरोध {carried_on} अझै खुला छ। दोहोरो सन्देशले त्यही अनुरोधको प्राथमिकता बढाएको छ।"
            if language == "ne"
            else f"Your earlier request {carried_on} is still open. This message raised its priority instead of opening a second case."
        )
    if request is not None:
        return (
            f"तपाईंको रिपोर्ट दर्ता भयो र {request.ref_code} सन्दर्भसहित सहयोग अनुरोध खोलिएको छ।"
            if language == "ne"
            else f"Your report is logged and a help request was opened for you as {request.ref_code}."
        )
    if report.duplicate_status == "duplicate":
        return (
            "तपाईंको यही जानकारी पहिले नै आइसकेको छ, नयाँ अनुरोध खोलिएन।"
            if language == "ne"
            else "The same information was already received, so no second request was opened."
        )
    if linked is not None:
        return (
            f"तपाईंको रिपोर्ट {linked.title} सँग जोडिएको छ।"
            if language == "ne"
            else f"Your report was attached to {linked.title}."
        )
    return (
        "तपाईंको रिपोर्ट दर्ता भयो, नजिकको कुनै घटनासँग अहिलेसम्म मेल खाएन।"
        if language == "ne"
        else "Your report is logged. It did not match any incident we know of yet."
    )


def _report_next_step(report, linked) -> str:
    """What happens to a report that did not become a help request. Being explicit
    here is what stops a person assuming help is on the way because they posted."""
    if linked is not None:
        return (
            "यो जानकारी आधिकारिक टोलीले हेरिरहेको घटनासँग जोडिएको छ।"
            if report.language == "ne"
            else "It has been added to an incident the Response Center is already watching."
        )
    return (
        "आधिकारिक निकायले हेर्ने पङ्क्तिमा राखिएको छ; यो अझै आधिकारिक सूचना होइन।"
        if report.language == "ne"
        else "It is queued for an operator to review. It is not an official warning by itself."
    )


def _public_incident(incident) -> dict | None:
    """Community users may see that their report joined a known situation, and its
    official status - never another person's private case details."""
    if incident is None:
        return None
    return {
        "id": incident.id,
        "ref_code": incident.ref_code,
        "title": incident.title,
        "incident_type": incident.incident_type,
        "district": incident.district,
        "evidence_state": incident.evidence_state,
        "official": incident.official_confirmation,
        "last_updated_at": iso(incident.last_updated_at),
        # The record's own address, not a screen route - see the note in api/incidents.py. A
        # community account gets the public projection of that endpoint, not the console one.
        "api_url": f"/api/incidents/{incident.id}",
    }


@router.get("/feed")
def feed(
    district: str | None = None,
    latitude: float | None = None,
    longitude: float | None = None,
    language: str = "en",
    user: User = Depends(require_permission("alerts:read")),
    db: Session = Depends(get_db),
) -> dict:
    return community_service.local_feed(
        db,
        user=user,
        district=district,
        latitude=latitude,
        longitude=longitude,
        language=language,
    )


@router.get("/activity")
def activity(
    user: User = Depends(require_permission("community:read_own")),
    db: Session = Depends(get_db),
) -> dict:
    """'MY REQUESTS' - this person's own reports, requests and notifications."""
    data = community_service.my_activity(db, user)
    data["user"] = {"alias": user.alias, "home_district": user.home_district}
    return data


@router.post("/requests")
def create_request(
    body: AssistanceRequestIn,
    user: User = Depends(require_permission("community:request")),
    db: Session = Depends(get_db),
) -> dict:
    request = assistance.create(
        db,
        user=user,
        description=body.description,
        request_type=body.request_type,
        assistance_types=body.assistance_types,
        latitude=body.latitude,
        longitude=body.longitude,
        location_text=body.location_text,
        people_count=body.people_count,
        medical_need=body.medical_need,
        immediate_danger=body.immediate_danger,
        trapped=body.trapped,
        minors_involved=body.minors_involved,
        elderly_or_disabled_involved=body.elderly_or_disabled_involved,
        incident_id=body.incident_id,
        report_id=body.report_id,
        language=body.language,
        attachments=[a.model_dump() for a in body.attachments],
        submitted_offline=body.submitted_offline,
    )
    return {
        "request": assistance.to_dict(db, request, victim_view=True),
        "timeline": assistance.timeline(db, request, victim_view=True),
        "receipt": communication.receipt_message(
            ref_code=request.ref_code,
            status=request.status,
            urgency=request.urgency,
            language=body.language,
            location_known=request.location_confidence in {"high", "medium"},
        ),
        "what_happens_next": communication.next_step(request.status, body.language),
        "sla": assistance.sla_info(request),
    }


@router.get("/requests")
def my_requests(
    user: User = Depends(require_permission("community:read_own")),
    db: Session = Depends(get_db),
) -> dict:
    """The 'MY REQUESTS' list: this person's own cases, newest first, open ones last.

    A person asking about their own case must never be shown a stranger's, so the
    filter is on the authenticated user id and nothing else - no query parameter can
    widen it.
    """
    rows = list(
        db.execute(
            select(AssistanceRequest)
            .where(AssistanceRequest.user_id == user.id)
            .order_by(desc(AssistanceRequest.created_at))
            .limit(50)
        ).scalars()
    )
    return {
        "items": [
            {
                **assistance.to_dict(db, row, victim_view=True),
                "what_happens_next": communication.next_step(row.status, row.language),
                "sla": assistance.sla_info(row),
            }
            for row in rows
        ],
        "count": len(rows),
        "generated_at": iso(utcnow()),
    }


@router.get("/requests/{ref_code}")
def read_request(
    ref_code: str,
    user: User = Depends(require_permission("community:read_own")),
    db: Session = Depends(get_db),
) -> dict:
    request = _own_request(db, ref_code, user)
    return {
        "request": assistance.to_dict(db, request, victim_view=True),
        "timeline": assistance.timeline(db, request, victim_view=True),
        "sla": assistance.sla_info(request),
    }


def _own_request(db: Session, ref_code: str, user: User) -> AssistanceRequest:
    request = assistance.get_by_ref(db, ref_code)
    # A ref code is guessable-ish, so ownership is checked on every read: another
    # person's case is simply not there.
    if request is None or (request.user_id != user.id and user.role == "community"):
        raise HTTPException(status.HTTP_404_NOT_FOUND, "No request with that reference")
    return request


@router.post("/requests/{ref_code}/cancel")
def cancel_request(
    body: CancelIn,
    ref_code: str,
    user: User = Depends(require_permission("community:request")),
    db: Session = Depends(get_db),
) -> dict:
    request = _own_request(db, ref_code, user)
    try:
        assistance.cancel_by_victim(db, request, user, body.reason)
    except assistance.StatusTransitionError as exc:
        raise HTTPException(status.HTTP_409_CONFLICT, str(exc)) from exc
    return {
        "request": assistance.to_dict(db, request, victim_view=True),
        "timeline": assistance.timeline(db, request, victim_view=True),
    }


@router.post("/offline/flush")
def flush_offline(
    body: OfflineFlushIn,
    user: User = Depends(require_permission("community:report")),
    db: Session = Depends(get_db),
) -> dict:
    """Accept a batch of items a phone queued while out of coverage.

    Each item is answered separately and re-stamped as an offline resubmission, so
    an update from yesterday is not silently presented as a report from now.
    """
    results: list[dict] = []
    for item in body.items:
        payload = dict(item.payload or {})
        payload["submitted_offline"] = True
        try:
            if item.kind == "report":
                parsed = ReportIn.model_validate(payload)
                report, linked, request = community_service.submit_report(
                    db,
                    user=user,
                    message=parsed.message,
                    report_type=parsed.report_type,
                    incident_type=parsed.incident_type,
                    latitude=parsed.latitude,
                    longitude=parsed.longitude,
                    location_text=parsed.location_text,
                    people_count=parsed.people_count,
                    medical_need=parsed.medical_need,
                    injuries=parsed.injuries,
                    language=parsed.language,
                    client_timestamp=parsed.client_timestamp,
                    submitted_offline=True,
                    needs_help=parsed.needs_help,
                    help_types=parsed.help_types,
                    immediate_danger=parsed.immediate_danger,
                )
                results.append(
                    {
                        "client_ref": item.client_ref,
                        "ok": True,
                        "kind": "report",
                        "id": report.id,
                        "urgency": report.urgency,
                        "incident_id": report.incident_id,
                        "assistance_ref": request.ref_code if request else None,
                    }
                )
            else:
                parsed = AssistanceRequestIn.model_validate(payload)
                request = assistance.create(
                    db,
                    user=user,
                    description=parsed.description,
                    request_type=parsed.request_type,
                    assistance_types=parsed.assistance_types,
                    latitude=parsed.latitude,
                    longitude=parsed.longitude,
                    location_text=parsed.location_text,
                    people_count=parsed.people_count,
                    medical_need=parsed.medical_need,
                    immediate_danger=parsed.immediate_danger,
                    trapped=parsed.trapped,
                    minors_involved=parsed.minors_involved,
                    elderly_or_disabled_involved=parsed.elderly_or_disabled_involved,
                    language=parsed.language,
                    submitted_offline=True,
                )
                results.append(
                    {
                        "client_ref": item.client_ref,
                        "ok": True,
                        "kind": "request",
                        "id": request.id,
                        "ref_code": request.ref_code,
                        "urgency": request.urgency,
                        "status": request.status,
                    }
                )
        except Exception as exc:  # noqa: BLE001 - one bad queued item must not lose the rest
            results.append({"client_ref": item.client_ref, "ok": False, "error": str(exc)[:300]})
    audit.record(
        db,
        action="offline_flush",
        entity_type=audit.ENTITY_USER,
        entity_id=user.id,
        actor=user,
        actor_kind="victim",
        new={"accepted": sum(1 for r in results if r["ok"]), "rejected": sum(1 for r in results if not r["ok"])},
    )
    db.commit()
    return {"results": results, "queued": len(body.items)}


@router.get("/incidents/{incident_id}")
def incident_context(
    incident_id: str,
    user: User = Depends(require_permission("incidents:read_public")),
    db: Session = Depends(get_db),
) -> dict:
    """Public context for one incident: what is officially known, nothing private."""
    incident = db.get(Incident, incident_id)
    if incident is None or incident.archived:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "That incident is not available")
    return {
        "incident": _public_incident(incident),
        "official_only": True,
        "reports": [
            community_service.report_to_dict(db, report)
            for report in community_service.recent_reports(db, incident_id=incident.id, limit=20)
            if report.duplicate_status != "duplicate"
        ],
    }
